language: R
cache: packages
latex: false
sudo: required
dist: trusty

r:
  - release

# Add GDAL, GEOS, proj, and units2 dependencies.
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

# Binary versions of packages to reduce build time.
r_binary_packages:
  - dplyr
  - markdown
  - readr
  - rmarkdown
  - tidyr
  - rlang
  - purrr
  - tibble
  - utils
  - jsonlite
  - stringr
  - xml2
  - rvest
  - httr
  - ggplot2
  - sf
